name: Java CI

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          server-id: github
          java-version: 1.8

      - name: Deploy to Sonatype Package Registry
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>\${env.ID}</id><username>\${env.USERNAME}</username><password>\${env.PASSWORD}</password></server></servers></settings>" > ~/.m2/settings.xml
#          RELEASE_REPO="\${env.ID}::default::\${env.RELEASE_URL}"
#          SNAPSHOTS_REPO="\${env.ID}::default::\${env.SNAPSHOTS_URL}"
#          mvn deploy -DaltReleaseDeploymentRepository="${RELEASE_REPO}" -DaltSnapshotDeploymentRepository="${SNAPSHOTS_REPO}" -DskipTests
          mvn deploy -P release -DskipTests
        env:
          ID: sonatype
#          RELEASE_URL: https://oss.sonatype.org/service/local/staging/deploy/maven2
#          SNAPSHOTS_URL: https://oss.sonatype.org/content/repositories/snapshots
          USERNAME: hocgin
          PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

